# serverless.yml
myNextApplication:
  component: "@sls-next/serverless-component@latest"
  inputs:
    roleArn: 'arn:aws:iam::183697223334:role/diby_prod_role_policy', # AWS ROLE 중복설정 방지
    bucketRegion: 'ap-northeast-2'    # S3 Bucket 지역 설정
    bucketName: '${env.BUCKET_NAME}'    # S3 Bucket 이름
    cloudfront:
      distributionId: '${env.DISTRIBUTION_ID}'  # cloudfront distribution ID
    domain : ["${env.SUB_DOMAIN}", "${env.DOMAIN}"]  # custom domain [ sub, domain ] --> ex. [ 'stag', 'diby.io ] / [ '', 'diby.io ]