import React from 'react';
import { useRouter } from 'next/router';
// Redux
import { useDispatch } from 'react-redux';
import { resetToken } from '../store/reducers/authReducer';
// Components
import withAuth from '../hoc/withAuth';
import Head from 'next/head';
import TestHomeOrganisms from '../components/organisms/testHomeOrganisms';

// Libraries
import { GoogleLogout } from 'react-google-login';

const Home = () => {
  const dispatch = useDispatch();
  const router = useRouter();
  const logout = async () => {
    try {
      dispatch(resetToken());
      await router.push('/login');
    } catch (e) {
      console.log(e);
    }
  };

  return (
    <div>
      <Head>
        <title>Diby 0.1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TestHomeOrganisms />
      <GoogleLogout
        clientId="318189383837-p36tbqlb9fd40n868q48u9c2eqgd0r96.apps.googleusercontent.com"
        buttonText="Logout"
        onLogoutSuccess={logout}
      />
    </div>
  );
};

export default withAuth(Home);
