import React from 'react';
import type { NextPage } from 'next';
// Components
import Head from 'next/head';
import TestHomeOrganisms from '../components/organisms/testHomeOrganisms';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Diby 0.1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TestHomeOrganisms />
    </div>
  );
};

export default Home;
