import React, { useEffect } from 'react';
import type { NextPage } from 'next';
import axios from 'axios';
import Head from 'next/head';
import { useRouter } from 'next/router';

const Home: NextPage = () => {
  const API: any = process.env.NEXT_PUBLIC_API;

  const router = useRouter();

  const initData = async () => {
    try {
      const res: any = await axios.get(API);
      console.log(res, 'ASDFASDF');
    } catch (e) {
      console.log(e);
    }
  };

  useEffect(() => {
    initData();
  });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>Diby 0.1 setting</div>
      <button type={'button'} onClick={() => router.push('/test')}>
        이동
      </button>
    </div>
  );
};

export default Home;
